# Generated by Django 3.2.1 on 2021-08-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0002_usuario_endereço'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario_endereço',
            new_name='Usuario_endereco',
        ),
    ]
